4

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -9,18 +9,20 @@ fi
 # Set the output filename
 PYFILEC="${PYFILE%.*}.pyc"
 
-# Create the __pycache__ directory
-mkdir -p "__pycache__"
-
 # Compile the Python script
 echo "Compiling $PYFILE ..."
-python3 -m compileall "$PYFILE"
+python3 -m py_compile "$PYFILE"
 
 # Check if compilation was successful
 if [ $? -eq 0 ]; then
     echo "Compilation successful."
-    mv "__pycache__/$PYFILEC" .
-    rm -r "__pycache__"
 else
     echo "Compilation failed."
+    exit 1
 fi
+
+# Move the compiled file to the current directory
+mv "__pycache__/$PYFILEC" .
+
+# Clean up the __pycache__ directory
+rm -r "__pycache__"
